data/urls.py
#from django.contrib import admin
from django.urls import path, re_path
from . import views

app_name = "data"

urlpatterns = [
    re_path(r'^data_input', views.csv_input, name = 'input'),
    re_path(r'^csv', views.csv_view, name = "csv"),
    re_path(r'^js_test', views.js_test, name = 'js'),
    re_path(r'^analyse_text', views.text_analyse, name = 'text'),
    re_path(r'^text_output', views.text_csv, name = 'text_output'),
    re_path(r'^transliterate', views.transliterate, name = 'transliterate'),
    re_path(r'^transliterate_output', views.transliterate_output, name = 'transliterate_output'),
    re_path(r'^random_sents', views.random_sents, name = 'random_sents'),
    re_path(r'^random_output', views.random_output, name = 'random_output')
]

project/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^about/$', views.about),
    re_path(r'^$', views.homepage),
    re_path(r'^accounts/', include('accounts.urls')),
    re_path(r'^articles/', include('articles.urls')), ##links to articles app
    re_path(r'^data/', include('data.urls')),
    re_path(r'^carpark/', include('carpark.urls')),
    re_path(r'^bootstrap/',  views.bootstrap_test)
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

data/models.py
from django.db import models
from django import forms

# Create your models here.
class Data(models.Model):
    text = models.TextField()

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50]

class Transliterate(models.Model):
    text = models.TextField()
    choices = (('0','UK IPA'), ('1','US IPA'), ('2','Klattese'), ('3','SAMPA'), ('4','ARPABET'))
    src = models.CharField(max_length = 2, choices = choices)
    dst = models.CharField(max_length = 2, choices = choices)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50]

class Random(models.Model):
    nouns = models.SlugField(blank = True)
    verbs = models.SlugField(blank = True)
    adj = models.SlugField(blank = True)
    prep = models.SlugField(blank = True)
    verbs_i = models.SlugField(blank = True)
    adv = models.SlugField(blank = True)

    def __str__(self):
        return self.title

data/forms.py
from django import forms
from . import models

class LoadData(forms.ModelForm):
    class Meta:
        model = models.Data
        fields = ["text"]

class Transliterate(forms.ModelForm):
    class Meta:
        model = models.Transliterate
        fields = ["text", "src", "dst"]

class Random(forms.ModelForm):
    class Meta:
        #model = models.Transliterate
        #fields = ["text", "src", "dst"]
        model = models.Random
        fields = ["nouns", "verbs", "adj","verbs_i","adv","prep"]

data/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms
import csv, io
from .models import Data
import requests
from django.http import JsonResponse
from . import PS_Rules

def random_sents(request):
    form = forms.Random()
    return render(request, 'data/random_sents.html', {'form': form})

def random_output(request):
    if request.method == "POST":
        form = forms.Random(request.POST)
        if form.is_valid():
            nouns = form.cleaned_data['nouns']
            verbs = form.cleaned_data['verbs']
            adj = form.cleaned_data['adj']
            prep = form.cleaned_data['prep']
            verbs_i = form.cleaned_data['verbs_i']
            adv = form.cleaned_data['adv']
            nouns = list(map(lambda x: (x,"",""), nouns.split()))
            verbs = list(map(lambda x: (x,"",""), verbs.split()))
            adj = list(map(lambda x: (x,"",""), adj.split()))
            prep = list(map(lambda x: (x,"",""), prep.split()))
            verbs_i = list(map(lambda x: (x,"",""), verbs_i.split()))
            adv = list(map(lambda x: (x,"",""), adv.split()))
            PS_Rules.nouns += (nouns)
            PS_Rules.verbs += (verbs)
            PS_Rules.verbs_i += (verbs_i)
            PS_Rules.adj += (adj)
            PS_Rules.adv += (adv)
            PS_Rules.prep += (prep)
            result = PS_Rules.run()
            return render(request, 'data/random_output.html', {'data': result})
    else:
        form = forms.Random()
    return render(request, 'data/random_output.html', {'data': ""})

def transliterate(request):
    if request.method == "POST":
        form = forms.Transliterate(request.POST)
        if form.is_valid():
            word = form.cleaned_data['text']
            src = int(form.cleaned_data['src'])
            dst = int(form.cleaned_data['dst'])
            #result = word
            #result = Transcription.transcribe(word, src, dst)
            '''
            response = HttpResponse(content_type = 'text/csv')
            response['Content-Disposition'] = 'attachment; filename="output.csv"'

            data = [[result]]
            writer = csv.writer(response)
            for row in data:
                writer.writerow(row)
            return response
            '''
            return render(request, 'data/transliterate_output.html', {'data': result})
    else:
        form = forms.Transliterate()
    return render(request, 'data/transliterate.html', {'form': form})

def transliterate_output(request):
    return render(request, 'data/transliterate_output.html', {'data': ""})

def text_analyse(request):
    form = forms.LoadData()
    return render(request, 'data/analyse_text.html', {'form': form})

def text_csv(request):
        if request.method == "POST":
            form = forms.LoadData(request.POST)
            if form.is_valid():
                words = form.cleaned_data['text']
                response = HttpResponse(content_type = 'text/csv')
                response['Content-Disposition'] = 'attachment; filename="output.csv"'

                data = analyse_text_csv(words)
                #write("try.csv", data)
                writer = csv.writer(response)
                for row in data:
                    writer.writerow(row)
                return response
        else:
            form = forms.LoadData()
        return render(request, 'data/analyse_text.html', {'form': form})

def analyse_text_csv(words):
    dic = {}
    for word in words.split():
        if word not in dic:
            dic[word] = 0
        dic[word] += 1
    output = list(map(lambda t: list(t), dic.items()))
    output.sort(key = lambda x: x[1], reverse = True)
    return output

def js_test(request):
    form = forms.LoadData()
    return render(request, 'data/js_test.html', {'form': form})
    #return render(request, 'data/js_test.html', {"data": JsonResponse({"try": "hello"})})

def read_csv(fname):
    new = []
    with open(fname, encoding = 'utf-8') as f:
        for row in csv.reader(f):
            new.append(row)
    return new

def process_words(words):
    data = read_csv("data/ipa.csv")
    dic = {}
    for row in data:
        dic[row[0]] = row[1:]
    result = [data[0]]
    for w in words.split():
        if w in dic:
            result.append([w]+dic[w])
    return result

def csv_view(request):
    if request.method == "POST":
        form = forms.LoadData(request.POST)
        if form.is_valid():
            words = form.cleaned_data['text']
            response = HttpResponse(content_type = 'text/csv')
            response['Content-Disposition'] = 'attachment; filename="output.csv"'

            data = process_words(words)
            #write("try.csv", data)
            writer = csv.writer(response)
            for row in data:
                writer.writerow(row)
            return response
    else:
        form = forms.LoadData()
    return render(request, 'data/csv_view.html', {'form': form})

def csv_input(request):
    form = forms.LoadData()
    return render(request, 'data/data_input.html', {'form': form})

data/templates/data/analyse_text.html
{% extends 'base_layout.html' %}

{% block content %}

<div class = "input-data">
  <h2> Input text </h2>
  <form class="site-form" action="{% url 'data:text_output' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
  </form>
</div>

{% endblock %}

data/templates/data/csv_view.html
{% extends 'base_layout.html' %}

{% block content %}

<div class = "output-data">
  <h1> Hello </h1>
</div>

{% endblock %}

data/templates/data/data_input.html
{% extends 'base_layout.html' %}

{% block content %}

<div class = "input-data">
  <h2> Input words </h2>
  <form class="site-form" action="{% url 'data:csv' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
  </form>
</div>

{% endblock %}

data/templates/data/js_test.html
{% extends 'base_layout.html' %}

{% load static %}
{% block content %}

  <script type="text/javascript">
    let counter = 0;
    function count() {
      counter++;
      document.querySelector('#counter').innerHTML = counter;
      /**
      if (counter % 10 === 0) {
        data = "{{data|safe}}";
        var json = JSON.parse(data);
        document.querySelector('#counter').innerHTML = data.try;
        document.querySelector('#counter').innerHTML = {{ form }};
      }
      */
    }
    document.addEventListener('DOMContentLoaded', function() {
      document.querySelectorAll('.color-change').forEach(function(button) {
        button.onclick = () => {
          document.querySelector('#counter').style.color = button.dataset.color;
        }
      });
      document.querySelector('#color-change').onchange = function() {
          document.querySelector('#counter').style.color = this.value;
      };

      document.querySelector('#task').onkeyup = () => {
        if (document.querySelector('#task').value.lenth > 0) {
          document.querySelector('#submit').disabled = false;
        } else {
          document.querySelector('#submit').disabled = true;
        }
      }

      document.querySelector("#new-task").onsubmit = () => {
        const li = document.createElement('li');
        li.innerHTML = document.querySelector('#task').value;

        document.querySelector('#tasks').append(li);
        document.querySelector('#task').value = '';
        return false;
      }
    });
  </script>

  <form id='form'>
    <input id = "currency" type="text">
    <input type = "submit" value="Get ExRate">
  </form>

  <h1 id = 'counter'>0</h1>
  <button onclick = "count()"> Click me </button>
  <button id = "green" class = "color-change" data-color = "green"> Green </button>
  <button id = "blue" class = "color-change" data-color = "blue"> Blue </button>
  <button id = "red" class = "color-change" data-color = "red"> Red </button>

  <select id = "color-change">
    <option value="red">Red</option>
    <option value="blue">Blue</option>
    <option value="black">Black</option>
    <option value="green">Green</option>
  </select>

  <ul id = "tasks">
  </ul>
  <form id = "new-task">
    <input id = "task" type="text" placeholder = "New Task">
    <input type = "submit">
  </form>

{% endblock %}

data/templates/data/random_output.html
{% extends 'base_layout.html' %}

{% block content %}

<div class = "random-output">
  <h3> {% for i in data %}
    <li> {{ i }} </li>
    {% endfor %}
  </h3>
</div>

{% endblock %}

data/templates/data/random_sents.html
{% extends 'base_layout.html' %}

{% block content %}

<div class = "input-data">
  <h2> Input words </h2>
  <form class="site-form" action="{% url 'data:random_output' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
  </form>
</div>

{% endblock %}

data/templates/data/transliterate.html
{% extends 'base_layout.html' %}

{% block content %}

<div class = "input-data">
  <h2> Input text </h2>
  <form class="site-form" action="{% url 'data:transliterate_output' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
  </form>
</div>

{% endblock %}

data/templates/data/transliterate_output.html
{% extends 'base_layout.html' %}

{% block content %}

<div class = "output-data">
  <h1> {{data}} </h1>
</div>

{% endblock %}