articles/urls.py
#from django.contrib import admin
from django.urls import path, re_path
from . import views

app_name = "articles"

urlpatterns = [
    #path('admin/', admin.site.urls),
    #re_path(r'^about/$', views.about),
    re_path(r'^$', views.article_list, name = "list"),
    re_path(r'^create', views.article_create, name = "create"),
    re_path(r'^(?P<slug>[\w-]+)/$', views.article_detail, name="detail")
]

data/urls.py
#from django.contrib import admin
from django.urls import path, re_path
from . import views

app_name = "data"

urlpatterns = [
    re_path(r'^data_input', views.csv_input, name = 'input'),
    re_path(r'^csv', views.csv_view, name = "csv"),
    re_path(r'^js_test', views.js_test, name = 'js'),
    re_path(r'^analyse_text', views.text_analyse, name = 'text'),
    re_path(r'^text_output', views.text_csv, name = 'text_output'),
    re_path(r'^transliterate', views.transliterate, name = 'transliterate'),
    re_path(r'^transliterate_output', views.transliterate_output, name = 'transliterate_output'),
    re_path(r'^random_sents', views.random_sents, name = 'random_sents'),
    re_path(r'^random_output', views.random_output, name = 'random_output')
]

project/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^about/$', views.about),
    re_path(r'^$', views.homepage),
    re_path(r'^accounts/', include('accounts.urls')),
    re_path(r'^articles/', include('articles.urls')), ##links to articles app
    re_path(r'^data/', include('data.urls')),
    re_path(r'^carpark/', include('carpark.urls')),
    re_path(r'^bootstrap/',  views.bootstrap_test)
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length = 100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    #thumb = models.ImageField(default='default.png', blank = True)
    #author = models.ForeignKey(User, default = None)

    #add author
    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50]

articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ["title","body","slug"]

articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms
import csv
# Create your views here.
def article_list(request):
    articles = Article.objects.all().order_by("date")
    return render(request, 'articles/article_list.html', {'articles':articles})

def article_detail(request, slug):
    #return HttpRespone(slug)
    article = Article.objects.get(slug = slug)
    return render(request, 'articles/article_detail.html', {'article': article})

@login_required(login_url = "/accounts/login/")
def article_create(request):
    if request.method == "POST":
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            # save article to db
            return redirect('articles:list')
    else:
        form = forms.CreateArticle()
    return render(request, 'articles/article_create.html', {'form': form})

def read_csv(fname):
    new = []
    with open(fname, encoding = 'utf-8') as f:
        for row in csv.reader(f):
            new.append(row)
    return new

def csv_view(request):
    response = HttpResponse(content_type = 'text/csv')
    response['Content-Disposition'] = 'attachment; filename="test.csv"'

    data = read_csv("test.csv")
    writer = csv.writer(response)
    for row in data:
        writer.writerow(data)
    return response

articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}

{% block content %}

<div class = "create-article">
  <h2> Create an article </h2>
  <form class="site-form" action="{% url 'articles:create' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Create">
  </form>
</div>

{% endblock %}

articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{% block content %}

<div class = "article_detail">
  <div class = "article">
    <!-- <img src="{{article.thumb.url}}"/> -->
    <h2> {{article.title}} </h2>
    <p> {{article.body}} </p>
    <p> {{article.date}} </p>
  </div>
</div>

{% endblock %}

articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1> Articles </h1>
    <div class = "articles">
      {% for article in articles %}
       <div class = "article">
        <h2> <a href="{% url 'articles:detail' slug=article.slug %}"> {{ article.title }} </a> </h2>
        <p> {{article.snippet}} </p>
        <p> {{article.date}} </p>
       </div>
      {% endfor %}
    </div>

{% endblock %}